In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
path = r"C:\Users\AKSHAT\Desktop\Data analyst Projects\E-Commerce Multi Table Olist\Data\Raw"

In [4]:
customers = pd.read_csv(r"C:\Users\AKSHAT\Desktop\Data analyst Projects\E-Commerce Multi Table Olist\Data\Raw\olist_customers_dataset.csv")
geolocation = pd.read_csv(r"C:\Users\AKSHAT\Desktop\Data analyst Projects\E-Commerce Multi Table Olist\Data\Raw\olist_geolocation_dataset.csv")
orderitem = pd.read_csv(r"C:\Users\AKSHAT\Desktop\Data analyst Projects\E-Commerce Multi Table Olist\Data\Raw\olist_order_items_dataset.csv")
payments = pd.read_csv(r"C:\Users\AKSHAT\Desktop\Data analyst Projects\E-Commerce Multi Table Olist\Data\Raw\olist_order_payments_dataset.csv")
reviews = pd.read_csv(r"C:\Users\AKSHAT\Desktop\Data analyst Projects\E-Commerce Multi Table Olist\Data\Raw\olist_order_reviews_dataset.csv")
orders = pd.read_csv(r"C:\Users\AKSHAT\Desktop\Data analyst Projects\E-Commerce Multi Table Olist\Data\Raw\olist_orders_dataset.csv")
products = pd.read_csv(r"C:\Users\AKSHAT\Desktop\Data analyst Projects\E-Commerce Multi Table Olist\Data\Raw\olist_products_dataset.csv")
sellers = pd.read_csv(r"C:\Users\AKSHAT\Desktop\Data analyst Projects\E-Commerce Multi Table Olist\Data\Raw\olist_sellers_dataset.csv")
Category_translation = pd.read_csv(r"C:\Users\AKSHAT\Desktop\Data analyst Projects\E-Commerce Multi Table Olist\Data\Raw\product_category_name_translation.csv")

print("All Datasets Loaded Successfully")

All Datasets Loaded Successfully

# Finding Null and Duplicated Values in Each Dataset

In [5]:
#Data Cleaning -:

# Customers

In [6]:
customers.isna().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [7]:
customers.duplicated().sum()

np.int64(0)

# Geolocation

In [8]:
geolocation.isna().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [9]:
geolocation.duplicated().sum()

np.int64(261831)

In [10]:
# Droping duplicates in Geolocation
geolocation.drop_duplicates(inplace=True)
print("-----------------------------------")
print("Dropped Duplicates Sucessfully")
print("-----------------------------------")
print("Count of Duplicates -:")
geolocation.duplicated().sum()

-----------------------------------
Dropped Duplicates Sucessfully
-----------------------------------
Count of Duplicates -:

np.int64(0)

# Orderitem

In [11]:
orderitem.isna().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [12]:
orderitem.duplicated().sum()

np.int64(0)

# Payments

In [13]:
payments.isna().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [14]:
payments.duplicated().sum()

np.int64(0)

In [15]:
payments.dtypes

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

# Reviews

In [16]:
reviews.isna().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [17]:
reviews.duplicated().sum()

np.int64(0)

In [18]:
#filling Values in Reviews 

reviews["review_comment_title"]=reviews["review_comment_title"].fillna("No Title")
reviews["review_comment_message"]=reviews["review_comment_message"].fillna("No Comment")
print("Values Filled Properly!!")
print("------------------------------------------")
reviews.isna().sum()

Values Filled Properly!!
------------------------------------------

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

# Orders

In [19]:
orders.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [20]:
orders.duplicated().sum()

np.int64(0)

In [21]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [22]:
orders[orders["order_delivered_customer_date"].isna()]['order_status'].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [23]:
orders[(orders["order_status"]=="delivered") & (orders["order_delivered_customer_date"].isna())]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaN,2017-12-18 00:00:00
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaN,2018-07-16 00:00:00
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaN,2018-07-24 00:00:00
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaN,NaN,2017-06-23 00:00:00
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaN,2018-06-26 00:00:00
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaN,2018-07-19 00:00:00

In [24]:
orders.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [25]:
orders.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [26]:
orders["order_purchase_timestamp"]=pd.to_datetime(orders["order_purchase_timestamp"],errors="coerce")
orders["order_approved_at"]=pd.to_datetime(orders["order_approved_at"],errors="coerce")
orders["order_delivered_carrier_date"]=pd.to_datetime(orders["order_delivered_carrier_date"],errors="coerce")
orders["order_delivered_customer_date"]=pd.to_datetime(orders["order_delivered_customer_date"],errors="coerce")
orders["order_estimated_delivery_date"]=pd.to_datetime(orders["order_estimated_delivery_date"],errors="coerce")

In [27]:
orders.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

# Products

In [28]:
products.isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [29]:
products.duplicated().sum()

np.int64(0)

In [30]:
products[products['product_category_name'].isna()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

In [31]:
products["product_category_name"] = products["product_category_name"].fillna("Unknown")
print("Values Filled Sucessfully")

Values Filled Sucessfully

In [32]:
products.isna().sum()

product_id                      0
product_category_name           0
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [33]:
products[products['product_weight_g'].isna()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Category Translation

In [34]:
Category_translation.isna().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [35]:
Category_translation.duplicated().sum()

np.int64(0)

In [36]:
Category_translation.dtypes

product_category_name            object
product_category_name_english    object
dtype: object

In [37]:
products.dtypes

product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

# Sellers

In [38]:
sellers.isna().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [39]:
sellers.duplicated().sum()

np.int64(0)

In [40]:
sellers.dtypes

seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

# Final Check of Data types

In [41]:
print("CUSTOMERS")
print(customers.dtypes)

print("\nGEOLOCATION")
print(geolocation.dtypes)

print("\nORDER ITEMS")
print(orderitem.dtypes)

print("\nORDER PAYMENTS")
print(payments.dtypes)

print("\nORDER REVIEWS")
print(reviews.dtypes)

print("\nORDERS")
print(orders.dtypes)

print("\nPRODUCTS")
print(products.dtypes)

print("\nSELLERS")
print(sellers.dtypes)

print("\nCATEGORY TRANSLATION")
print(Category_translation.dtypes)

CUSTOMERS
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

GEOLOCATION
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

ORDER ITEMS
order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

ORDER PAYMENTS
order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

ORDER REVIEWS
review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

ORDERS
order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

PRODUCTS
product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

SELLERS
seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

CATEGORY TRANSLATION
product_category_name            object
product_category_name_english    object
dtype: object

In [42]:
#Date Columns Fix
reviews["review_creation_date"]= pd.to_datetime(reviews["review_creation_date"])
orderitem["shipping_limit_date"]= pd.to_datetime(orderitem["shipping_limit_date"])

# Exporting Final Datasets

In [43]:
path = r"C:\Users\AKSHAT\Desktop\Data analyst Projects\E-Commerce Multi Table Olist\Data\Cleaned"

os.makedirs(path, exist_ok=True)

In [44]:
customers.to_csv(path + r"\olist_customers_cleaned.csv", index=False)
geolocation.to_csv(path + r"\olist_geolocation_cleaned.csv", index=False)
orderitem.to_csv(path + r"\olist_order_items_cleaned.csv", index=False)
payments.to_csv(path + r"\olist_order_payments_cleaned.csv", index=False)
reviews.to_csv(path + r"\olist_order_reviews_cleaned.csv", index=False)
orders.to_csv(path + r"\olist_orders_cleaned.csv", index=False)
products.to_csv(path + r"\olist_products_cleaned.csv", index=False)
sellers.to_csv(path + r"\olist_sellers_cleaned.csv", index=False)
Category_translation.to_csv(path + r"\product_category_translation_cleaned.csv", index=False)

print("All 9 datasets exported successfully!")

All 9 datasets exported successfully!

In [45]:
geolocation.shape

(738332, 5)